README.md
docs/install.rst

- Build dependencies should be specified
- Runtime dependencies too, specify which Postgres versions we support
- Makes it more obvious that an existing primary Postgres can be used

Improve documentation.

---

src/bin/pg_autoctl/pgctl.c

We parse the output of pg_controldata and expect English output. Force the
environment to be in C locale when calling pg_controldata so that we do not
depend on the user locale settings here.
The other output parsing we do is on pg_ctl --version, where we only parse
the version string. As that's only digits and dots ([[:digit:].]+), we don't
need to set the LANG=C in that case. I think. At least this patch does
nothing for this case.
Fix #26.

Manually set LANG=C when running pg_controldata.

---

docs/ref/reference.rst
src/bin/pg_autoctl/cli_do_monitor.c
src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/monitor/Makefile
src/monitor/expected/drop_extension.out
src/monitor/expected/dummy_update.out
src/monitor/metadata.c
src/monitor/metadata.h
src/monitor/node_active_protocol.c
src/monitor/pg_auto_failover.c
src/monitor/pgautofailover--1.0--dummy.sql
src/monitor/sql/drop_extension.sql
src/monitor/sql/dummy_update.sql
tests/pgautofailover_utils.py
tests/test_extension_update.py

The pg_autoctl tool embeds the version of the extension that it is
compatible with on the monitor. The idea is that those versions are kept in
sync at the source code and packaging level, and a given pg_autoctl command
line is compatible with a single version of the monitor.
At startup on the monitor the command `pg_autoctl run` checks the monitor's
version and if necessary runs a command `ALTER EXTENSION ... UPDATE TO ...`
the expected version. It is expected that the extension packaging provides
the necessary upgrade paths.
On the keeper, we check that the version number of the extension on the
monitor is compatible with our expectations, and exit before entering the
main loop when that's not the case. We refrain from doing "upgrade at a
distance" and tell the admin (who's reading the …

Implement checking and upgrading of the pgautofailover extension.

---

docs/install.rst

Add the manual steps to install our repositories and packages, in addition to the quick install method requiring the scary `curl | sudo bash` stanza.
Fixes #13.

Fix install recipe

---

Dockerfile
docs/operations.rst
docs/ref/reference.rst
src/bin/pg_autoctl/cli_do_monitor.c
src/bin/pg_autoctl/cli_enable_disable.c
tests/pgautofailover_utils.py
tests/test_basic_operation.py

The feature was already there and the CLI hidden in our DEBUG tooling,
because we were not sure at the time of the initial implementation how to
expose the feature to our users.
Now that we have the enable|disable subcommands already, it looks like it is
a good fit for the maintenance feature.
Fixes #33.

Implement pg_autoctl enable|disable maintenance CLI.

---

src/bin/pg_autoctl/Makefile
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/state.c

Some of our C files are missing headers and compile then fails on FreeBSD.
I'm not sure how compile passes in other systems / compilers, and the fix
seems relevant and general enough for all platforms.
Fixes #32.

Fix missing include header.

---

docs/operations.rst
docs/ref/reference.rst
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor_config.c
src/bin/pg_autoctl/monitor_pg_init.c
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/primary_standby.h
tests/pgautofailover_utils.py
tests/test_auth.py

we can now configure auth param in pg_hba for following users
Monitor:
autoctl_node : user to connect to monitor from pg_autoctl nodes
Nodes:
pgautofailover_monitor : user to connect to pg_autoctl nodes from the monitor
Replication user auth mode is also set to provided value if the replication user password is also set.

Add --auth option to configure authentication method

---

Dockerfile
src/bin/pg_autoctl/Makefile

Now that we're using $(shell $(PG_CONFIG) --libs) to have the list of
librairies we depend on, we must align the build dependencies of
pg_auto_failover with the Postgres build dependencies on the platform where
we build.
In debian, that means having build dependencies towards readline
support (that's libedit), pam, zlib, xml, xstl, and selinux.
See #34.

Fix dockerfile build-dependencies.

---

src/monitor/metadata.c

String buffer returned by TextDatumGetCString was in
SPI memory context, and it is invalidated upon SPI_finish()
We set active memory context here so that data will continue
to be available after SPI_finish(). It would be reclaimed
by next memory context reset to occur after completion of the call.

Fix memory context when performing version check

---

src/bin/pg_autoctl/ipaddr.c

When using PPTP protocol some interfaces are exposed without an if_addr
field at all, which would trip our IP address discovery code and cause a
segfault.
Fixes #40.

Fix IP address inquiries when ifa_addr is NULL.

---

src/bin/pg_autoctl/fsm_transition.c
tests/pgautofailover_utils.py
tests/test_basic_operation.py

Replication slot record remains in pg_replication_slots after
primary gets demoted to be secondary. This commit explicitly
removes the record.
Fixes #42

Drop replication slot after failover being demoted to secondary

---

src/bin/pg_autoctl/pgctl.c

Rather than playing fast and loose with sprintf and static buffers that
might or might not be big enough chunks of memory, use the PostgreSQL client
side library for dynamic string buffers where it makes sense.
Fixes #54

Use PQExpBuffer facility in more places.

---

src/bin/pg_autoctl/pgctl.c

`get_current_GUC_value` had an invalid memory usage. Removing the function was easier than fixing. 
Fixes #60

Remove get_current_GUC_value function

---

docs/conf.py

Fixes #61.
With that setting when doing `make man` we now have the following output:
```
$ ls -l ./docs/_build/man/
total 240
-rw-r--r--  1 dim  staff  85016 Sep 19 14:05 pg_auto_failover.1
-rw-r--r--  1 dim  staff  24316 Sep 19 14:05 pg_autoctl.1
-rw-r--r--  1 dim  staff  11116 Sep 19 14:05 pg_autoctl.5
```
Those pages can be installed in the packages script and are actually covering the `pg_autoctl` tool itself.

Add support for producing pg_autoctl man pages.

---

src/bin/pg_autoctl/pgsql.c

We used to get received_lsn value from a view. We now directly call `pg_last_wal_receive_lsn()` function to get received lsn value.

Change lsn retrieval method to directly call a UDF

---

src/bin/pg_autoctl/keeper.c

This message was causing too much noise in the log without
providing any benefit

Remove unnecessary warning message from the log

---

docs/ref/configuration.rst
docs/ref/reference.rst
src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/keeper_config.h
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgctl.h
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/primary_standby.c

This could have been a one-liner, but raises the question of the hard-coded
choice for the backup directory. The major reason of the target PGDATA
already existing is that it's targeting a mount-point. Then our default
choice of ${PGDATA}/../backup for the pg_basebackup target is not a good
one, because the renaming of the directory will cross file system boundaries
and not be atomic anymore.
This patch then allows to configure the backup directory. In passing, the
default value now includes the nodename, so that it's easier to run tests
environments with multiple instances on the same machine.
See #64 and #74.

Fix creating a secondary server in an already existing directory.

---

src/bin/lib/subcommands.c/commandline.c
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_enable_disable.c
src/bin/pg_autoctl/cli_formation.c
src/bin/pg_autoctl/cli_root.c
src/bin/pg_autoctl/cli_root.h
src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/cli_systemd.c
src/bin/pg_autoctl/main.c

Our nested command and sub-commands parsing is not compatible with the
default GNU getopt behavior where they will re-order the command line so
that users are free to mix options and arguments as they want.
When we are on the final sub-command though, we could re-enable the default
behavior of GNU getopt_long for more flexibility to the user. That's what we
do with this patch, making it possible to use either form for the same
command as in the following example:
$ pg_autoctl -q config get --pgdata /tmp/sm/a postgresql.port
3001
$ pg_autoctl config get postgresql.port --pgdata /tmp/sm/a -q
3001
Without this patch, only the first case works.
As most of our commands only process options, only two places need to be
adjusted to make that behavior available. The other commands don't need this …

Improve options and arguments parsing.

---

src/bin/lib/subcommands.c/runprogram.h
src/bin/pg_autoctl/cli_root.h
src/bin/pg_autoctl/file_utils.c
src/bin/pg_autoctl/file_utils.h
src/bin/pg_autoctl/main.c
src/bin/pg_autoctl/systemd_config.c

In some cases:
- we would use argv[0] as the binary to invoke again in sub-programs
- execv() would fail with "No such file or directory"
Then our handling of execv() failure was leaving a process and a pipe
behind, leading to a strange process tree and a bad situation.
This patch fixes the code so that we get the realpath for the currently
executed program (using proper API in macOS but a heuristic for other OSes),
and fixes the error handling at the execv() call site too.

Fix execv() failure handling and argv0 usage.

---

src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h

We produce the JSON on the server-side thanks to Postgres support functions
there. That's also much less code to write.

Implement `pg_autoctl show state --json`.

---

src/bin/pg_autoctl/ini_file.c

Without this patch when reading the configuration file and it's missing a
section entirely, it would be an error even for optional parameters. This
situation mostly happens when upgrading pg_autoctl and the new version has
implemented a new configuration section, which didn't exist previously, and
has default parameters that you can run with.

Tolerate missing optional INI options in missing sections.

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
tests/pgautofailover_utils.py
tests/test_basic_operation.py
tests/test_create_run.py

This allows for using the same command the first time and at following
boots, making it even easier than before to integrate in docker or k8s
environments. Provisioning and startup can now be the same if needed.

Implement pg_autoctl create postgres|monitor --run.

---

src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h

We refuse to own an already running Postgres cluster. Then it's fair for us
to also accept that the user might just stop the Postgres instance and give
it to us again. This patch makes us recognize the situation and proceed with
our initialisation steps in that case.
Fixes #111.

Fix initialiazing an already existing Postgres cluster.

---

src/bin/pg_autoctl/cli_systemd.c
src/bin/pg_autoctl/systemd_config.c

In normal operations we might remove or replace PGDATA, when doing a full pg_basebackup for instance, during a failover. It turns out that systemd doesn't like that.
Instead of using PGDATA as the WorkingDirectory we can use the User home directory instead. That should be safe.

Refrain from using PGDATA as the systemd service WorkingDirectory.

---

src/bin/pg_autoctl/pgctl.c

The escaping rules are not per parameter in the connection string, but global to the connection string.

Fix generating the primary_conninfo.

---

src/bin/pg_autoctl/fsm.c
src/bin/pg_autoctl/loop.c

Only ensure the current state when we didn't receive a new one from the monitor, otherwise we might start a demoted Postgres!

Fix when to ensure state in the keeper FSM loop.

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_config.c
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/monitor_config.c
src/bin/pg_autoctl/monitor_config.h
tests/test_auth.py
tests/test_basic_operation.py
tests/test_extension_update.py

Keeper now checks the state of monitor and restart it if it is found to be not active.
Fixes :  #86

Ensure the monitor's Postgres is running as part of `pg_autoctl run`

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h

Rather than doing multiple and different queries for the cases when the
local Postgres is a primary or a standby, do a single query that knows how
to fetch the metadata we are interested in.

Review how to get the local Postgres metadata.

---

src/bin/pg_autoctl/Makefile
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_config.c
src/bin/pg_autoctl/cli_do_fsm.c
src/bin/pg_autoctl/cli_do_monitor.c
src/bin/pg_autoctl/cli_enable_disable.c
src/bin/pg_autoctl/cli_get_set_properties.c
src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/ini_file.c
src/bin/pg_autoctl/ini_file.h
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/keeper_config.h
src/bin/pg_autoctl/monitor_config.c
src/bin/pg_autoctl/monitor_config.h
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/bin/pg_autoctl/state.c
src/bin/pg_autoctl/state.h

Have the option parsing for --json implemented in the common function
cli_getopt_pgdata and implement JSON formatted output in (almost) all
commands.

Implement --json for (almost) all commands.

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h
src/bin/pg_autoctl/loop.c
tests/pgautofailover_utils.py
tests/test_ensure.py

Even at pg_autoctl start we might be given a transition order by the
monitor, such as SINGLE to WAIT_PRIMARY. We should make sure that Postgres
is running (as per the current state SINGLE) before calling the transition
function, as it might need that pre-condition to be true.

Ensure current state before reaching the assigned state.

---

src/bin/pg_autoctl/cli_show.c

We don't actually call into the pg_ctl client in those code paths, so trying
to initialise this setting is not doing us any good and opens an error
condition.

Refrain from setting pgSetup.pg_ctl for pg_autoctl show state|nodes.

---

src/monitor/expected/monitor.out
src/monitor/node_active_protocol.c
src/monitor/sql/monitor.sql

When registering a standby, we need the primary node to have reached the
SINGLE state already. There's a possibility that the primary has been
registered (INIT/SINGLE), but has not reached the SINGLE state yet.

Fix a race condition at initialization time.

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/primary_standby.c

Review postmaster.pid stale pid detection.
Make it so that we know how to make progress when we read a stale pid from
the postmaster.pid file. This might happen after a kill -9 on the Postgres
service or in other unusual circumstances.

Stale postmaster pid

---

src/bin/pg_autoctl/monitor.c

We need only 7 columns and we know their name, a proper writing of the SQL
query also allows to be compatible with more versions of the monitor's
schema. Good practices and all that.

Fix printLastEvents by fixing the SQL projection.

---

.travis.yml
src/bin/lib/subcommands.c/runprogram.h
src/bin/pg_autoctl/pgctl.c

Fixes builds with the tools in the OpenBSD and Alpine Linux systems.
Fixes #95.
Fixes #118.
Fixes #148.
Fixes #153.

Avoid using stdin/stdout/stderr as variable names

---

src/monitor/pg_auto_failover.c

That's the only time when background worker processes are started, and we do
need those.

Error out when the pgautofailover is not in shared_preload_libraries.

---

.editorconfig

Github respects this file and basically all editors have support for it. Either
through plugin or out of the box.  https://editorconfig.org/

Add .editorconfig so indentation is done right across editors

---

docs/ref/reference.rst
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_root.c

This allows removing a node from the monitor when it's been declared dead
already.

Implement pg_autoctl drop monitor and drop node --nodename --nodeport.

---

src/bin/pg_autoctl/debian.c
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/file_utils.c
src/bin/pg_autoctl/file_utils.h
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/monitor_config.c
src/bin/pg_autoctl/pgsetup.c

And reads are moved to a dedicated function for easy ignoring fopen as a banned
function there.

Open files in a safe way

---

docs/quickstart.rst
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/env_utils.c
src/bin/pg_autoctl/file_utils.c
src/bin/pg_autoctl/monitor_config.c
src/bin/pg_autoctl/monitor_pg_init.c
src/bin/pg_autoctl/pgsetup.c

Follow the Quickstart and fix everything that we broke in the release making.

QA work following the docs quickstart

---

docs/security.rst
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/primary_standby.c

Things this does:
1. Remove last mentions to never merged `--ssl` option.
2. Make clear that `--ssl-self-signed` should be prefered over `--no-ssl`, both in error and help messages
3. Add warning when using `--no-ssl`

Improve docs related to SSL options

---

src/bin/pg_autoctl/Makefile

Implicit function declarations and wrong return types cause confusing errors
during development and are never behave like you want.

Always error out on warnings indicating obvious mistakes

---

src/bin/pg_autoctl/Makefile

This makes sure you don't have to run "make clean" anymore to get a
correct build when you change header files. To get the same support for
the monitor extension, you should compile your postgres with --enable-depend.

Make CC generate dependency information for Makefile

---

tests/pgautofailover_utils.py
tests/test_basic_operation.py
tests/test_ensure.py
tests/test_extension_update.py

Sleeping with smaller resolution makes sure that when something takes 150ms we
don't wait a full second, but instead only 200ms.

Speed up tests a bit

---

tests/pgautofailover_utils.py
tests/test_auth.py
tests/test_basic_operation.py
tests/test_create_run.py
tests/test_ensure.py
tests/test_skip_pg_hba.py
tests/test_ssl_cert.py
tests/test_ssl_self_signed.py

The `other_node` parameter in the tests infects all APIs and is somewhat
fragile, since it only supports one other node, even though there are
potentially more.
This PR removes the `other_node` parameters throughout the testing framework
and instead adds cluster level support for sleeping and calling `communicate`
on a NSPopen object. These new functions make sure to flush the unix pipes of
all postgres nodes in the cluster, this way deadlocks should not happen
anymore.
This was also discussed shortly here:
https://github.com/citusdata/pg_auto_failover/pull/226#discussion_r408009938

Integrate other_node functionality into the cluster

---

src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/primary_standby.c

The normalize we had didn't actually work correctly, since it was doing it on
`pgSetup` instead of `newPgSetup`. So the result was basically thrown away.
This moves the normalization to `pg_setup_init`, which seems reasonable because
`normalize_filename` is a no-op when the directory does not exist.

Normalize pgdata in a better place

---

src/bin/lib/subcommands.c/commandline.c
src/bin/lib/subcommands.c/commandline.h
src/bin/pg_autoctl/main.c

This would have saved some time debugging a failing test.
And it's also more UNIX compliant in general.

Return non-zero exit code when command parsing fails

---

src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/pgsetup.c

There were two issues:
1. When using `--formation ...` on the monitor it would not pass the loaded
sslmode, because the wrong pgSetup was used.
2. When initialized with `--no-ssl` an empty `sslModeStr` would be stored.
Fixes #239

Fix problems with empty sslmode in show uri command

---

src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/monitor_config.c

This does three things:
1. Make "show uri" output consistent for keeper and monitor
2. Add --monitor flag to get only the monitor uri
3. Fix sslmode in a uri being empty on old clusters
NOTE: Before this change on a keeper `pg_autoctl show uri` would output the
string for the formation that the keeper was a part of. This is not possible
anymore now without passing `--formation the-formation-string`. If it is deemed
useful to have this old behaviour behind a flag, it would be quite easy to add.
Another option is to have it stay the default, but add an `--all` flag that can
be used to show all formation strings on the keeper.
Fixes #238

Improve "show uri" command

---

src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper_pg_init.c
tests/test_ssl_self_signed.py

If we create the postgresql.conf before starting Postgres, we can include
the citus extension in the shared_preload_libraries and be done with that
step without having to later pg_ctl restart.

Avoid requiring a restart of Postgres during our initialization steps.

---

src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_root.h
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/primary_standby.h
src/monitor/health_check_worker.c
tests/test_auth.py

We don't actually need this user or its HBA rules, since authentication
does not need to succeed for the healtcheck to work. The healthcheck only
checks if the port is open on the specified host and it speaks the
postgres protocol.

Don't create pgautofailover_monitor user anymore

---

src/bin/pg_autoctl/cli_enable_disable.c

This makes it extra clear to users that additional actions are needed to
complete the setup.

Use log_warn instead of log_info when pg_autoctl is not running

---

src/monitor/Makefile

We do the same in the citus repo. This makes sure that in dev environments (or
building from source normally) old sql migration files are not accidentally
left behind.

Make sure old pgautofailover files are removed before install

---

src/monitor/node_active_protocol.c
tests/test_basic_operation.py

Otherwise our state machine gets confused. Also it does not make sense to
allow for manual failover when the current state of the cluster is not a
stable "primary/secondary" state anyway.

Prevent manual failovers when there's no node currently "primary".

---

src/monitor/Makefile

Without this change debian packages would only include
pgautofailover--1.0.sql and pgautofailover--1.3.sql

Include upgrade scripts in make install correctly

---

src/bin/pg_autoctl/Makefile
src/monitor/Makefile

We already had this for pg_auto_ctl, but not for the monitor extension. This
caused packaging to not include the expected CFLAGS, most importantly `-g` so
no debug info was created.

Allow setting custom CFLAGS in the monitor

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_config.c
src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_root.h
src/bin/pg_autoctl/file_utils.h
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgctl.h
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
tests/pgautofailover_utils.py

Also make our functions exported in the PG_AUTOCTL_DEBUG facilities, to make
it easy to test and fix them. Since they're published there now, also use
them in our test suite rather than re-implementing a special-purpose version
of them in Python.

Cleanup, fix, refactor pgsetup Postgres pidfile utilities.

---

tests/network.py
tests/pgautofailover_utils.py

This is done by putting some more (aggressive) timeouts in places that
should not take long. Without this teardown would get stuck on test failure,
because then our cleanup commands would get stuck.

Make sure teardown does not get stuck

---

src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/lock_utils.c
src/bin/pg_autoctl/lock_utils.h
src/bin/pg_autoctl/service.c
src/bin/pg_autoctl/service_monitor.c
src/bin/pg_autoctl/service_postgres_ctl.c
src/bin/pg_autoctl/supervisor.c

The semaphore ID is passed to child processes using a environment variable.
This way we never conflict with other semaphores.
We need to either remove the semaphore cleanup or we should store the semaphore
id in the pidfile too.

Use a private semaphore

---

docs/ref/reference.rst
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/primary_standby.h
src/bin/pg_autoctl/state.c
src/monitor/expected/create_extension.out
src/monitor/node_active_protocol.c
src/monitor/node_metadata.c
src/monitor/node_metadata.h
src/monitor/pgautofailover.control
src/monitor/pgautofailover.sql
src/monitor/sql/create_extension.sql
tests/test_auth.py
tests/test_create_standby_with_pgdata.py

This allows users to use their favorite backup and restore options when
preparing to add a standby node to pg_auto_failover.
We still have a restriction that we don't know how to accept an already
running standby: we would need to check the primary conninfo authentication
options in use, the replication slot, etc. So we still bail out in that
case.
See #101.

Allow adding a standby node from an exiting PGDATA directory.

---

src/bin/pg_autoctl/cli_do_service.c
src/bin/pg_autoctl/service_postgres_ctl.c
src/bin/pg_autoctl/signals.c
src/bin/pg_autoctl/signals.h
src/bin/pg_autoctl/supervisor.c

The supervisor process should relay the urgency of the SIGQUIT signal down
to its sub-processes and it's now the case. Also, the intermediate Postgres
controller service should handle SIGQUIT properly: terminate Postgres, exit
with EXIT_CODE_QUIT (zero), and let the supervisor handle the situation.
WIP: will add `atexit()` calls to manage the resource cleanup (pidfile, semaphore).

Improve handling of SIGQUIT in pg_autoctl processes.

---

src/bin/pg_autoctl/lock_utils.c
src/bin/pg_autoctl/main.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/service_monitor_init.c

Note: We can't move the pidfile cleanup to the atexit stage easily enough because of using a local supervisor variable, and we don't really need to do that anyway because of the way we handle SIGQUIT and stale pidfiles anyway.
See #272.

Move the log semaphore clean-up function to atexit().

---

src/bin/lib/subcommands.c/runprogram.h
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/string_utils.c
src/bin/pg_autoctl/string_utils.h

This can be a pretty long operation and being in the dark for its whole
duration is not a great user experience.

Arrange to forward pg_basebackup output while it's running.

---

src/bin/pg_autoctl/cli_perform.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h

Refuse to proceed with default group 0 when there is more than one group
registered in the target formation on the monitor, ask the user to specify
the target group with using the --group option.
Otherwise, suprises might ensue.

Improve pg_autoctl perform failover/switchover default --group.

---

src/monitor/pgautofailover--1.2--1.3.sql

When using Postgres < 12 we can't ALTER an ENUM TYPE within a transaction,
and the extension upgrade script runs in a transaction. Which means we can't
upgrade pgautofailover when using Postgres 12 at the moment.
The fix requires dropping the enum type entirely, keeping the data in its
text form, and casting the data again to the new enum type after it's been
created. It's the long and painful way, but it is required for our support
of Postgres 10 and 11.

Fix pgautofailover extension upgrade script from 1.2 to 1.3.

---

.gitignore

These are generated when you have compiled postgres with --with-llvm,
which enables JIT support for the monitor extension.

Ignore .bc files

---

src/bin/pg_autoctl/cli_perform.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h

We use the same approach as when applying a new setting: listen to
notification messages from the monitor and parse them until we see that we
have reached the expected target state.
In this case it's easy, we now we reached the target state when we see the
notification of a node reaching state primary.

Command pg_autoctl perform failover now waits until failover is done.

---

CHANGELOG.md
README.md
docs/architecture.rst
docs/fault-tolerance.rst
docs/fsm/node-state-machine
docs/operations.rst
docs/ref/configuration.rst
docs/ref/reference.rst

Nothing terribly interesting, just a few tyops and a formatting error found when reading the docs.

doc: minor fixes to spelling and formatting

---

src/bin/pg_autoctl/service_postgres.c

Like the comment says we would get an error message like this on startup
sometimes:
```
16:31:53 21530 ERROR 2020-06-19 16:31:51.463 CEST [21801] ERROR:  database "postgres" already exists
```

Don't show postgres startup messages on succesful startup

---

src/bin/pg_autoctl/file_utils.c

Make sure to catch in case the memory allocation, and exit gracefully in case of memory exhaustion. This falls in the "unlikely to happen" bucket but makes static analysis easier and is generally good hygiene to follow.

Add guards on memory allocation failure

---

src/bin/pg_autoctl/pgsetup.c
tests/pgautofailover_utils.py
tests/test_enable_ssl.py

The `--ssl-ca-file` option is only required when using `verify-ca` or
`verify-full`. This change allows people to use the following options:
```bash
pg_autoctl --server-cert node.cert --server-key node.key --ssl-mode require
```

Do not always require --ssl-ca-file for custom SSL

---

src/bin/pg_autoctl/cli_config.c
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h

When Postgres is known to be running we can update our control data
information in the cache from a SQL query rather than doing another fork()
and exec() on the pg_controldata binary and parsing its output.
There are still a few too many calls to pg_controldata after this patch, but
at least we don't do it every second anymore when Postgres is running fine.

Reduce how often we exec() pg_controldata.

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/service_keeper.c

Ensure that when we could register successfully to the monitor but then
failed to create our local state file, we cancel (ROLLBACK) the
registration. Otherwise we have a node on the monitor and no way to relate
that node to the current pg_autoctl process.

Review the registering process & transaction.

---

src/bin/pg_autoctl/primary_standby.c

The file in question is named postgresql.conf, make sure to reference it by its correct name to avoid user confusion.

Fix name of config file in error message

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_do_service.c
src/bin/pg_autoctl/cli_enable_disable.c
src/bin/pg_autoctl/cli_formation.c
src/bin/pg_autoctl/cli_perform.c
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/cli_systemd.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/pidfile.c
src/bin/pg_autoctl/pidfile.h
src/bin/pg_autoctl/service_keeper.c
src/bin/pg_autoctl/service_keeper_init.c
src/bin/pg_autoctl/service_monitor.c
src/bin/pg_autoctl/service_monitor_init.c
src/bin/pg_autoctl/service_postgres_ctl.c
src/bin/pg_autoctl/supervisor.c
src/bin/pg_autoctl/supervisor.h

Our new pg_autoctl upgrade procedure will make it possible to have a
supervisor process running with version 1.4 and the node-active process
being restarted from disk with version 1.5. It is then important that we are
able to provide this information to the users.
Currently, the information fits in our output for pg_autoctl version when
using the JSON format, so that's where it is available.
To be able to have that information, we need the services themselves to
publish it. For that, we invent per-service pidfiles and have a new pidfile
format that contains the version string.

Report services version strings in pg_autoctl version --json.

---

src/bin/pg_autoctl/cli_config.c
src/bin/pg_autoctl/config.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/bin/pg_autoctl/primary_standby.c

A bug in Postgres prevents WAL recycling on standby nodes when we use the
function pg_replication_slot_advance() to maintain their LSN position. In
this patch we work around the bug to avoid it by just not installing our
replication slots on the standby nodes when we're running a Postgres version
with the bug. That's 11.0 to 11.8 included, and 12.0 to 12.3 included.
Fixes #283.

Only use replication slots on standby nodes for good Postgres versions.

---

docs/ref/configuration.rst
src/bin/pg_autoctl/primary_standby.c
src/monitor/health_check.h
src/monitor/health_check_metadata.c
src/monitor/health_check_worker.c
src/monitor/pg_auto_failover.c

Also remove a misleading log line saying that we're waiting for Postgres to
start (serve) when actually we are waiting for the monitor to have done at
least one health check with the node.
Also change the default HealthCheckPeriod from 20s down to 5s.
See #332.
Fixed #329.

Log and notify node health changes.

---

src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgsetup.c

We need to copy over at pgSetup.pgdata and pgSetup.pg_ctl before calling
into the pg_controldata binary.

Fix bug in pg_setup_controldata.

---

src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/service_keeper.c

Some parts of the code need to distinguish between failure to connect to a
(remote) Postgres instance and failure to execute a query, or retrieve the
expected result from the query. Make the information available in the PGSQL
structure.

Track connection status / failures.

---

src/bin/pg_autoctl/keeper_pg_init.c

When we return false from keeper_pg_init_and_register() the initialisation
process is then exited with an error code, and the supervisor is going to
try again to run the TRANSIENT service successfully. This makes sense when
we failed to contact to monitor or had another kind of intermitent failure.
When the problem is that it's all good and you should use --run or the
pg_autoctl run command, well, early exit with success code is better:
arguably we did our job.
Fixes #348.

Exit early with EXIT_CODE_QUIT in pg_autoctl create when possible.

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/keeper_config.h

The code now expects the replication slot name to be set a certain way, same
as the application_name. As it's now enforced, make it so that our users
can't edit it the way they would prefer it. It's an implementation detail
now.

Get rid of configuration setting for replication slot name.

---

src/bin/pg_autoctl/keeper.c

As we renew the keeper->postgres.pgSetup cache on each round, we need to
manually make sure to re-install the current values we have in cache when
Postgres is not running. That said, we might also reach that code path at
pg_autoctl start-up when Postgres is not yet running.

In some cases, we still need to call pg_controldata.

---

src/monitor/node_active_protocol.c
tests/test_multi_standbys.py

When we remove the old primary, its reported state is still that of a
primary. We might have moved on to a new primary already though, and in that
case we want to process the old-primary the same way we would a secondary.
To fix, consider the goalState rather than the reportedState, and filter out
the DRAINING, DEMOTE, and DEMOTE_TIMEOUT as meaning that we have a primary,
by testing with CanTakeWritesInState() rather than StateBelongsToPrimary().
Fixes https://github.com/citusdata/pg_auto_failover/issues/353.

Fix dropping the old-primary node.

---

src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/pidfile.c
src/bin/pg_autoctl/pidfile.h

And when it's running and --json is used, match the same format as in the
command pg_autoctl show file --pid --contents --json, adding the status of
the pids (running, or stale).
Fixes #310

Fix pg_autoctl status when pg_autoctl is not running.

---

src/bin/pg_autoctl/keeper_config.c

The replication slot name is computed from the nodeId, which is not expected
to change once registered.

Don't change the replication slot name at reload.

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_get_set_properties.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/monitor/node_active_protocol.c
src/monitor/node_metadata.c
src/monitor/node_metadata.h
src/monitor/pgautofailover.sql

We add a new parameter --formation (defaults "default") to the commands so
that we now support running them from a monitor node.
Fixes #351.

pg_autoctl get|set formation number-sync-standbys from the monitor.

---

src/monitor/node_active_protocol.c
src/monitor/node_metadata.c

We had re-opened the failover to unstable states where the current goal
state and reported state are not the same, and that led to problems as per
issue https://github.com/citusdata/pg_auto_failover/issues/369.
Fixes #369.

Fix when to allow for a failover in multiple standbys.

---

docs/tutorial.rst

Turns out that what we thought were sentence fragments were actually a result of RTD not rendering code blocks. See 
6efcbf2 for details.

Fix tutorial typos, and make sure all code blocks are displayed

---

src/bin/pg_autoctl/pgsetup.c

That's not a very interesting race condition, really.

Reduce chatter when postmaster.pid is read empty.

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_get_set_properties.c
src/bin/pg_autoctl/cli_perform.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/monitor/group_state_machine.c
src/monitor/node_active_protocol.c
src/monitor/node_metadata.h
src/monitor/pgautofailover.sql
tests/pgautofailover_utils.py
tests/test_basic_operation.py
tests/test_multi_async.py

This command allows to promote a given node (by name, or the current local
one) to being the primary on a group. When the node is already a primary, no
action is taken and the command returns true immediately.

Implement pg_autoctl perform promotion.

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/service_keeper.c

This allows more flexibility for extending the behavior at reload.

Move the keeper reload_configuration into a hooks array.

---

src/bin/pg_autoctl/fsm_transition.c
src/monitor/group_state_machine.c
src/monitor/node_active_protocol.c

When removing a standby node just after creating it, and before running its
pg_autoctl service, then it's still in the CATCHINGUP state, and the primary
is waiting in the JOIN_PRIMARY state. At removal of the standby, the primary
should feel free to set itself back to PRIMARY again.
Fixes #393.

Fix a corner case which leaves a node in JOIN_PRIMARY state.

---

src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/primary_standby.h
src/monitor/node_active_protocol.c
tests/test_multi_maintenance.py

A bug has been found where if we have a single standby and it's in maintenance, we can't add another standby. That's not nice, and to fix it, we need to allow registering a new standby node while the primary is in the WAIT_PRIMARY state. The reason for this state could either be that a standby is in maintenance, or that another standby is concurrently registering to the primary.
To fix, we now lift the limitation that only one standby can be registered at a single time. This way we can register a standby even when the primary is in the WAIT_PRIMARY state already, or even in the JOIN_PRIMARY or APPLY_SETTINGS state. For this to work, some responsibilities are added to the client side of things, where it's now necessary to check for the replication slot creation before moving on, even when …

Allow registering multiple standbys concurrently

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/primary_standby.c

Getting out of the secondary state means we should not ensure the secondary
state anymore, it's already too late. We had cases of Postgres being
restarted because of that, and if that happens when we don't have a recovery
setup in place, then Postgres restarts as a primary. Then it can't be a
secondary again anymore, WAL are "corrupted".

When secondary, don't ensure current state before a transition.

---

src/bin/pg_autoctl/cli_enable_disable.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/service_keeper.c

After seeing the following happen in Travis, we could process some error
conditions as transient and retry. It would be best for test stability, and
also for users who script around some pg_autoctl commands.
ERROR Monitor ERROR:  deadlock detected
ERROR Monitor DETAIL:  Process 21381 waits for ShareLock on transaction 532; blocked by process 21382.
ERROR Monitor Process 21382 waits for ExclusiveLock on advisory lock [16385,822708183,0,11]; blocked by process 21381.
ERROR Monitor HINT:  See server log for query details.
ERROR Monitor CONTEXT:  while updating tuple (0,11) in relation "node"
ERROR Monitor SQL statement "UPDATE pgautofailover.node SET goalstate = $1, statechangetime = now() WHERE nodeid = $2"
ERROR SQL query: SELECT pgautofailover.stop_maintenance($1)
ERROR SQL params: '2' …

Implement a retry policy for deadlocks and other transient failures.

---

src/bin/pg_autoctl/primary_standby.c

See #402 and https://github.com/citusdata/pg_auto_failover/pull/402/commits/d519d643e665cea114cf4c8bf40b1b0312f5f30e in particular.
Should fix #408.

Refrain from validating primary conninfo when we don't have a primary.

---

src/bin/pg_autoctl/service_keeper.c
tests/pgautofailover_utils.py
tests/test_basic_operation.py

We might fail to connect to the monitor early in keeper_node_active()
function and that was not a code path taken into account. Oops.

Fix network partition detections.

---

src/bin/pg_autoctl/pgsetup.c

When we optimised away calls to `pg_controldata`, we missed that parts of the code depend on it having been run previously. This is another case of cache invalidation games, and we force getting the control data again when we don't have it in `pg_setup_pgdata_exists`. Given that fix, then we unblock a loop at https://github.com/citusdata/pg_auto_failover/blob/master/src/bin/pg_autoctl/service_postgres_ctl.c#L273 which otherwise is an infinite loop.
Fix #412.

Fix taking control of an already running  Postgres instance.

---

src/bin/pg_autoctl/primary_standby.c

We connect to the primary using the pgautofailover_replicator username to
check if the replication slot has been created already on the primary, but
in that case we didn't have another use for the connection, no clean-up
happens later.
Close the connection as soon as we have the information we are looking for.
We reconnect each time anyway.
Fixes #450.

Force closing the connection used to check replication slots.

---

src/monitor/group_state_machine.c
src/monitor/node_metadata.c
src/monitor/node_metadata.h
tests/test_multi_async.py

We might reach intermediate states on the newly elected primary such as
wait_primary/primary and in that situation we can already move forward and
have the secondary nodes re-configured to follow the new primary.

Fix when to ProceedWithMSFailover after a candidate is selected.

---

src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/primary_standby.h
src/bin/pg_autoctl/service_monitor.c
src/bin/pg_autoctl/service_postgres.c
src/bin/pg_autoctl/service_postgres_ctl.c
src/bin/pg_autoctl/state.c
src/bin/pg_autoctl/state.h
tests/test_basic_operation.py

When we don't own the Postgres subprocess, we can't ensure that a pending
monitor upgrade is being done properly. This is mostly a problem when
upgrading from 1.3.1 to 1.4(.0, fix going to appeart in .1).
Fixes #434

Ensure that the monitor owns the Postgres (sub-)process.

---

src/bin/pg_autoctl/cli_do_show.c
src/bin/pg_autoctl/ipaddr.c
src/bin/pg_autoctl/ipaddr.h
src/bin/pg_autoctl/pghba.c
src/bin/pg_autoctl/pghba.h

Postgres HBA implementation with hostname is pretty picky, in order to be
secure enough. The reverse DNS lookup requirements are often missed, and
sometimes hard or impossible to achieve (Cloud VM environments).
As more users get confused with their hostname based setup, we should
provide more guidance when that's possible.
See #452.

Implement HBA hostname DNS checks, and warn users when needed.

---

src/monitor/node_active_protocol.c
src/monitor/node_metadata.c

In terms of available that's worse than using ANY, and Postgres
implementation of FIRST/ANY has nothing to do with our implementation of the
candidate priority anyway. We don't want to insist on transaction being
preferably committed by any given standby, we have FAST_FORWARD after all.

Refrain from using FIRST %d in synchronous_standby_names.

---

docs/tutorial.rst

At the cost of complicating the commands a little, I've removed warnings and MOTD output from the SSH output.
Also registered the server ssh fingerprints at the start rather than having it prompt the user. In one code block we sshed to node B twice, and if a user copied and pasted both commands it would fail because the fingerprint prompt would consume the pasted input.

Remove distractions from SSH output

---

src/bin/pg_autoctl/cli_do_monitor.c
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pghba.c
src/bin/pg_autoctl/primary_standby.c
src/monitor/formation_metadata.c
src/monitor/group_state_machine.c
src/monitor/node_active_protocol.c
src/monitor/node_metadata.h

Normalize the use of the notation "node %d \"%s\" (%s:%d)" in every message
that shows a node to the user. That helps a lot with debugging, and also,
when people name things, they usually like using the name again.

Always use node id and node name in messages.

---

src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/file_utils.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/lock_utils.c
src/bin/pg_autoctl/parsing.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pidfile.c
src/bin/pg_autoctl/supervisor.c

We avoid using malloc in most of the code base, and still require it when
reading a file from disk. Some places in the code didn't get the memo that
read_file() and read_file_if_exists() leak memory, and the caller needs to
call free().
Also, because we only have a handful of malloc() failed error messages, it's
a good thing to always use the same error message format. And this format
should not require memory allocation of course. I believe %m is okay with
that.
Fixes #473

Review memory/malloc errors and potential leaks.

---

src/bin/pg_autoctl/fsm.c
src/bin/pg_autoctl/fsm_transition.c
src/monitor/node_active_protocol.c
tests/pgautofailover_utils.py
tests/test_multi_standbys.py

When removing a node we might end up with a race condition if the primary in
parallel is already in a transition, or in any other case when
ProceedGroupState on the primary doesn't change the assigned state.
In that case we now force a new APPLY_SETTINGS state to be assigned, so that
the primary has a chance of fetching the (new) current synchronous standby
names settings.
Also, it might be that a node has been dropped while reaching APPLY_SETTINGS
itself, so in the transition from APPLY_SETTINGS to PRIMARY we also
implement fsm_apply_settings, to protect against race conditions.
Any transition to PRIMARY now also calls fsm_apply_settings.
Fixes #446, fixes #476.

Review APPLY_SETTINGS transitions in cases including node removal.

---

src/monitor/node_active_protocol.c
tests/test_auth.py
tests/test_basic_operation.py

Because we assign both SECONDARY and PRIMARY in the same monitor
ProceedGroupState call, we might end up with the primary fetching its new
synchronous_standby_names from the monitor before when the secondary has
made it to its new state.
With the previous coding, the primary would then retrieve '', meaning sync
replication is disabled, when what's needed is '*'.
We add some needed test coverage from the situation and fix it in the
monitor by returning '*' as soon as the other node is assigned SECONDARY
rather than only after it has reported the state.

Fix when we switch synchronous_standby_names to '*'.

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_do_fsm.c
src/bin/pg_autoctl/fsm_transition.c

Here are the first few things I ran into while investigating https://github.com/citusdata/pg_auto_failover/pull/483. See commit messages for details.

Miscellaneous fixes for --disable-monitor mode

---

src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c

Use our new function `ipaddrGetLocalHostname` directly on `config->hostname` so that we can continue with the hostname properly set.

Fix bug in monitor hostname discovery

---

src/monitor/group_state_machine.c

As soon as a node has been assigned secondary we may assign catching-up
instead if the monitor finds it unhealthy.
See #488

Review when to assign catching-up on unhealthy secondary.

---

src/bin/pg_autoctl/pgsql.c

And when get a non-ok result from the server, as in other code paths, we
clear the result and close the connection.

Fix error code path in pgsql clear_results.

---

src/bin/pg_autoctl/fsm.c
src/monitor/group_state_machine.c
tests/test_multi_ifdown.py
tests/test_multi_maintenance.py

When handling a group with multiple standby nodes but only one of them is a
candidate for failover, some adjustments are needed in order for the FSM to
coorectly move forward when the non-candidates are showing first.
In practice, we should:
- refrain from assigning PRIMARY to a WAIT_PRIMARY node when a standby is
reaching SECONDARY if that standby has a candidatePriority = 0,
- start the re-join process of a demoted primary even when the new primary
is still transitioning between wait_primary and primary, we don't need a
stable state there,
- and as a consequence of the first item, allow a transition from
wait_primary to join_primary when adding a secondary to the new primary
node, if the secondary being added has candidatePriority = 0.
See …

Fix race conditions in multiple-standby Group FSM for failover.

---

.travis.yml
src/monitor/group_state_machine.c
src/monitor/node_metadata.c
tests/pgautofailover_utils.py
tests/test_basic_operation.py
tests/test_multi_ifdown.py
tests/test_multi_maintenance.py

When a node gets out of maintenance and back in the group, we might have to
change the syncrhonous_standby_names on the primary to include the node
again. For that, if the primary node is in a stable PRIMARY state, thanks to
other standby nodes being available, we need to assign APPLY_SETTINGS to the
current primary.

Fix synchronous_standby_names when disabling maintenance.

---

Makefile
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_do_fsm.c
src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/config.c
src/bin/pg_autoctl/config.h
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/keeper_config.h
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/nodestate_utils.c
src/bin/pg_autoctl/nodestate_utils.h
src/bin/pg_autoctl/parsing.c
src/bin/pg_autoctl/parsing.h
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/service_keeper.c
src/bin/pg_autoctl/state.c
tests/pgautofailover_utils.py
tests/test_monitor_disabled.py
tests/test_multi_standbys.py

In the current version the pg_autoctl process is the parent process of the
Postgres main process. Except when using --disable-monitor, which makes no
sense, so here we fix that.
It is now possible to control and run a Postgres process under a pg_autoctl
process without using a monitor, as in the following example:
$ pg_autoctl create postgres --auth trust --no-ssl --disable-monitor --run
$ PG_AUTOCTL_DEBUG=1 pg_autoctl do fsm assign single
The `pg_autoctl do fsm assign` command now edits the keeper state file, and
the FSM transition that is necessary is then implemented in the keeper loop
as usual.

Fix --disable-monitor to work with the parenting of Postgres model.

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgctl.h
src/bin/pg_autoctl/pgsetup.c
src/monitor/group_state_machine.c

When more than one Postgres version is found in $PATH a classic way to
target a specific one, for Postgres contributors and extension authors,
consists of using PG_CONFIG.
With this PR we make it so that pg_autoctl also follows PG_CONFIG and use
the pg_ctl PATH in the same directory as the pg_config setup that way in the
environment.
In passing, cleanup the pg_ctl_version() API to stop leaking memory out of
its local stack/heap.

Use PG_CONFIG has a hint to choose one of multiple Postgres versions.

---

NOTICE
cgmanifest.json

Component Governance detector cannot detect git components currently, so
we should register them manually for SDL.
Example result: https://msdata.visualstudio.com/Database%20Systems/_componentGovernance/citus-ha?_a=components&typeId=4985361&alerts-view-option=active
We also have `pg` and `subcommands`, as far as I remember now we kinda own `subcommands` and for `pg` we seem to take only two files, it seemed not necessary to add whole postgres repo for this.

Register components manually

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_root.h
src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/file_utils.c
src/bin/pg_autoctl/file_utils.h
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgctl.h
src/bin/pg_autoctl/pgsetup.c

This improves default integration with debian/ubuntu packaging system for
Postgres where the postgresql-common package installs a pg_config version in
the main PATH and keeps major-dependent versions of pg_ctl in their specific
directories, that are not automatically added to PATH.
Fixes #514

Use pg_config from the PATH when we can't find a pg_ctl.

---

src/bin/pg_autoctl/lock_utils.c

Only define `union semun` on Linux. Tested building pg_auto_failover with this change on
- Fedora 33
- Alpine 3.12.0
- Mac OS 10.14.6
- OpenBSD 6.8

Fix build for *BSD

---

src/monitor/group_state_machine.c
tests/pgautofailover_utils.py
tests/test_basic_operation.py
tests/test_multi_async.py
tests/test_multi_ifdown.py

The FSM state wait_primary embeds the information that there is no solution
to failover, and as such there is no point in changing the state of the node
to draining or otherwise, as no failover process is going to kick-in.

Fix unhealthy nodes processing when wait_primary.

---

Makefile
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/cli_do_tmux.h

Implement a new set of options that allows the following command:
$ make NODES=3 NODES_ASYNC=1 NODES_SYNC_SB=0 cluster
Given that command we directly get the following setup, ready for QA and
tests and debugging:
Context |    Name |                   Setting | Value
----------+---------+---------------------------+-----------------------------------
formation | default |      number_sync_standbys | 0
primary |   node1 | synchronous_standby_names | 'ANY 1 (pgautofailover_standby_2)'
node |   node1 |        replication quorum | true
node |   node2 |        replication quorum | true
node |   node3 |        replication quorum | false
node |   node1 |        candidate priority | 50
node |   node2 |        candidate priority | 50
node |   node3 |        candidate priority | 0

Improve our tmux integration for QA and testing.

---

src/monitor/group_state_machine.c
tests/pgautofailover_utils.py
tests/test_basic_operation.py
tests/test_multi_async.py

When a node with candidate priority zero is back online and we implement the
catchingup to secondary transition, refrain from assigning PRIMARY to the
leader node: we don't have a candidate for failover and so should remain
wait_primary.
Fixes #528

Fix FSM when a non-candidate node is back online.

---

src/monitor/group_state_machine.c
tests/test_multi_async.py

We can now be in wait_primary and still lose a secondary node, when that
node has a candidate priority set to zero.
Fixes #529

Fix assigning catchingup to unhealthy secondaries.

---

src/bin/pg_autoctl/cli_get_set_properties.c
src/bin/pg_autoctl/cli_show.c
tests/pgautofailover_utils.py

The command logs at the INFO level the new synchronous_standby_names value
after having applied the given number-sync-standbys, and that was wrong due
to using the default groupId parsed to -1 at the getopts level.
Fixes #531

Fix pg_autoctl set formation number-sync-standbys log output.

---

.travis.yml

I realised after pressing merge that #216 didn't actually add `black` as
part of CI. This addresses that, so that we know formatting is always
done.

Actually run black in CI

---

Makefile
src/bin/pg_autoctl/azure.c
src/bin/pg_autoctl/azure.h
src/bin/pg_autoctl/azure_config.c
src/bin/pg_autoctl/azure_config.h
src/bin/pg_autoctl/cli_do_azure.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_root.h
src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/cli_do_tmux.h
src/bin/pg_autoctl/cli_do_tmux_azure.c

The following commands allow to easily deploy a testing or QA environment
for pg_auto_failover using Azure VMs, which looks more like what typical
users and customers are using than our default `make cluster` approach where
all the nodes are running on localhost.
In particular we can test system integration and packages based
provisioning, so that's better for end-to-end QA.
Here's the list of new commands provided:
pg_autoctl do azure
+ provision  provision azure resources for a pg_auto_failover demo
+ tmux       Run a tmux session with an Azure setup for QA/testing
+ show       show azure resources for a pg_auto_failover demo
deploy     Deploy a pg_autoctl VMs, given by name
create     Create an azure QA environment
drop       Drop an azure QA environment: resource group, network, VMs …

Implement pg_autoctl do azure commands.

---

src/bin/pg_autoctl/file_utils.c
src/bin/pg_autoctl/file_utils.h
src/bin/pg_autoctl/pgctl.c

In recent debian releases /bin is a symlink to /usr/bin, which means we're
going to find pg_config twice on that system. But it's twice the same entry,
and we can deduplicate and realize we only have one entry actually.
Fixes #545

Deduplicate PATH entries that are symlinks resolving to other PATH entries

---

src/bin/lib/subcommands.c/runprogram.h

The read() call might have left garbage in the buffer after the last byte,
so enforce end-of-string at the boundary returned.

Fix bytes mangling opportunity.

---

Makefile

Without that we can't do
$ make build
$ make interactive-test

Typo fix from a previous merge.

---

Makefile
src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/cli_do_tmux.h

This PR allows to setup an interactive testing/QA cluster with tmux with
full specifications of nodes replication settings. Before that the code was
conflating the replicationQuorum and the candidatePriority of nodes, and
that was limiting our testing abilities.
When unspecified, nodes are all created with `--candidate-priority 0`. Then it
is possible to specify one or more candidate priorities, which are used in
the order given. When more nodes are created than priorities are given, we
use the last specified priority again and again.
For instance `--node-priorities 50,0 --nodes 3` results in using 50,0,0 as the
respective priorities for the nodes thus created.

make NODES=3 NODES_ASYNC=2 NODES_PRIOS=50,0 NODES_SYNC_SB=0 cluster

---

src/bin/pg_autoctl/cli_do_tmux.c

I had some paths in my PATH that contained spaces, because of WSL. This caused
issues with the tmux script, because these were neither escaped nor quoted.

Fix tmux script when having PATH with spaces

---

src/monitor/node_active_protocol.c

When a user runs the same command twice in a row, such as with the
following, make it so that the second time just works. It didn't because we
failed to observe that setting the candidate priority to zero could be a
non-changer if that's already the current value of the setting.
pg_autoctl set node candidate-priority --name node3 0
We could also skip the operation entirely, but this has two drawbacks:
- the client implementation would then need to decide if it has to wait
for the apply-settings steps to happen or immediately return,
- more importantly, if there's a problem with synchronous_standby_names it
might be good that setting a value to its current setting, thus applying
no changes, forces a cache invalidation of the primary's setup.
Fixes #526

Refrain from preventing changes that are not really changes.

---

docker-compose.yml
docs/ref/reference.rst
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_common.h
src/bin/pg_autoctl/cli_create_drop_node.c
src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_show.c
src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/ipaddr.c
src/bin/pg_autoctl/ipaddr.h
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor_config.c
src/bin/pg_autoctl/monitor_pg_init.c
src/bin/pg_autoctl/pghba.c
src/bin/pg_autoctl/pghba.h
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/primary_standby.h

With this option pg_autoctl edits the pg_hba.conf for Postgres to grant
connection privileges on the detected LAN for the --dbname database and for
the --username user.
The LAN detection is done the same way as with the monitor.
The idea is to simplify steps for running demos using docker-compose, where a single command can be used to start processes in each contained, and sync between running containers and extra actions isn't easily implemented.

Implement pg_autoctl create postgres --pg-hba-lan option.

---

src/bin/pg_autoctl/supervisor.c

The waitpid() reading of the conditions that lead to a process being
reported are more complex than the previous implementation assumed.

Fix supervisor messages about exited services.

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h

We should refrain from calling strlcpy() on one of the function arguments.

Fix memory management issue in monitor_register_node.

---

src/bin/pg_autoctl/main.c

I have tested the change locally on pg versions 10, 11, 12 and 13, `rmtree` no longer segfaults for PG versions >= 12.
How I tested it:
1) Get monitor and primary up and running.
2) When setting up the secondary we set PGDATA to a mount point so if we `rmtree` it, we'll get a busy device error. 
`rmtree` logs that error using `pg_log_warn` which would segfault if we don't call `pg_logging_init` before hand.
None of the testing is automated, it was done with a finicky docker-compose setup and manually executing commands on the secondary node's container.
If we want to add a test case for this, I don't know how to do it in the existing testing framework.

Add pg_logging_init for PG version 12 and above

---

src/bin/pg_autoctl/Makefile
src/monitor/Makefile

Microsoft has a set of guidelines for hardening GNU/Linux executables and linkables. If a`USE_SECURITY_FLAGS` command line option or environment variable is defined, we add some flags to both compiler and llvm linker flags.
Note that the CFLAGS for shared libraries and executables are different. Hence different set of security flags in Makefiles.
`make USE_SECURITY_FLAGS=1` or `USE_SECURITY_FLAGS=1 make` will build the project with the security flags.

Add opt-in security flags

---

README.md

We don't use "latest" anymore because that might be confusion (latest stable
version?), we use "master" now, the name of the git default branch.
Fixes #640.

Fix links to our documentation.

---

src/bin/pg_autoctl/cli_enable_disable.c
src/bin/pg_autoctl/cli_get_set_properties.c
src/bin/pg_autoctl/cli_perform.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/monitor_pg_init.c
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/service_keeper.c

It seems that pgsql_execute_with_params() during its lifetime has been
inconsistently altered. The latest version notes in the comments that the
connection is not persistant to facilitate error handling. However that was not
entirely true and several parts of the code assumed it to not be true. Others
assumed to be true and failed to release the connection once used.
For the sake of clarity, the function will now explicitly close the connection
that has used, regardless of wether it is a new or existing connection. That
simplifies most of the code and plugs the connection leaks.
It also unconvers an inconsistency on the connections used for notification. The
code mixed the connection it was using to listen to events from the monitor and
with others. A new PGconn member has been added in …

Plug connection leaks found during profiling

---

src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor_pg_init.c
src/bin/pg_autoctl/pgctl.c

Make this a warning only: this extra operation is meant to help diagnose the
situation when CREATE EXTENSION fails. We might fail to locate the control
file of the extension when Postgres would succeed, so we should still
proceed.
Fixes #585.
Fixes #645.

Review find_extension_control_file() error handling.

---

src/bin/pg_autoctl/cli_do_tmux_azure.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pghba.c
src/bin/pg_autoctl/supervisor.c

Fix memory leak allocated by createPQExpBuffer()

Fix memory leak allocated by createPQExpBuffer()

---

src/bin/pg_autoctl/cli_systemd.c
src/bin/pg_autoctl/systemd_config.c

The current user might be root or another interactive system user so that
it's possible to use sudo to write the systemd unit files. Typically, the
"postgres" user is not granted sudo privileges, and that's a good thing.
With this changes, if pg_autoctl show systemd is used from the root account
with a --pgdata created by the "postgres" user, we expect to obtain the
proper systemd unit file.

Use PGDATA owner for the systemd service file.

---

src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/primary_standby.c

If the upstream server isn't ready for a replication connection being made,
then both pg_rewind and then pg_basebackup will fail. The current code would
attribute the error to pg_rewind itself though, and continue with a full
base backup, where it might be possible to connect and rewind later.

Check that a "replication" connection is possible before pg_rewind.

---

src/bin/pg_autoctl/cli_config.c
src/bin/pg_autoctl/parsing.c
src/bin/pg_autoctl/parsing.h
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgsetup.c

The previous coding was wrong on several grounds:
First, pg_control_version only changes when there is a catalog
incompatibility in a given Postgres major version. For instance Postgres
12.6 still uses pg_control_verison 1201.
Second, the pg_setup_standby_slot_supported() function logic was missing
some cases and would return false even though replication slots are
supported on the standby nodes.
See #594

Fix parsing pg version string for replication slots support on standby.

---

docs/ref/pg_autoctl_perform_failover.rst
docs/ref/pg_autoctl_perform_promotion.rst
src/bin/pg_autoctl/cli_perform.c
src/bin/pg_autoctl/demoapp.c
src/bin/pg_autoctl/keeper_config.c
src/bin/pg_autoctl/keeper_config.h
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h

Also implement a new command line parameter --wait for the pg_autoctl
perform promotion|switchover|failover commands.
Fixes #604.

Implement a new configuration option listen_notifications_timeout.

---

Makefile
src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/cli_do_tmux.h
src/bin/pg_autoctl/cli_do_tmux_azure.c
src/bin/pg_autoctl/main.c

This makes sure memory leaks in subprocesses are also detected
correctly.

Also spawn valgrind for pg_autoctl subprocesses

---

Dockerfile
Makefile
valgrind/.gitignore

This runs in a docker container where we have valgrind installed and allows
to check for some memory leaks.

make valgrind-session.

---

src/bin/pg_autoctl/monitor.c

The formation context parts should also be an array, even when we know it
contains a single element for now.
Fixes #694

Fix pg_autoctl show settings --json output.

---

src/monitor/group_state_machine.c
src/monitor/node_metadata.c

When trying to find if a candidate has already been selected, avoid choosing
a node that is in WAIT_PRIMARY. As we don't change the state of such a node
when it becomes unhealthy, that might lead to strange results when two
failover situations happen one after another.
Also guard demoted to cachingup transitions to only happen when the current
primary is known healthy.

Fix an often failing test by improving the Group FSM robustness.

---

Makefile
src/monitor/node_metadata.c
src/monitor/node_metadata.h
tests/test_multi_alternate_primary_failures.py
tests/test_multinode_alternate_primary_failures.py

Assume that there exists a healthy three datanode cluster having datanodes named
node1, node2, node3. Assume that node1 is the primary and it fails. The cluster
will correctly demote node1 and promote node2 to primary. When node2 fails, the
cluster would fail to reach a stable state due to node2 getting stuck in
draining state.
The culrpit is GetPrimaryOrDemotedNodeInGroup which contains logic to try to
find a demoted primary in case that a healty primary is not existing. To do
that, it traverses an ordered by name list of nodes in the group. When it finds
the first node that is either a demoted or draining or taken out for
maintainance primary, it chooses it and stops looking further. In the example
above, note that the ordered by name list starts with node1, which would satisfy
the …

Complete transition of a second (or greater) failed primary

---

src/monitor/health_check.h
src/monitor/health_check_metadata.c
src/monitor/health_check_worker.c

Log monitor health changes as events.

---

src/bin/pg_autoctl/cli_do_misc.c
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_root.h
src/bin/pg_autoctl/cli_service.c
src/bin/pg_autoctl/parsing.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgctl.h
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/pgsetup.h
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/primary_standby.h
src/bin/pg_autoctl/service_postgres.c

Implement crash recovery (target immediate, timeline current).
When pg_rewind would fail because the target PGDATA was not shutdown
properly, have Postgres do a round of crash recovery to clean-up the data
directory and only then resort to pg_rewind.
Now pg_rewind can fail for other reasons:
INFO  pg_rewind: connected to server
INFO  pg_rewind: servers diverged at WAL location 0/2C000060 on timeline 21
INFO  pg_rewind: fatal: could not find previous WAL record at 0/2C000060: invalid record length at 0/2C000060: wanted 24, got 0
See #653

Feature crash recovery before pg rewind

---

src/monitor/health_check_worker.c

It is possible for a dynamic background worker to fail registration. It is
unlikely, yet possible. If that happens during the monitor's launch of
healthcheck workers, the function StartHealthCheckWorker() will emmit an info
level log message saying to acknowledge the fact. Then the caller of the
function will try again to register that worker until it succeeds or the process
receives a signal to terminate. If the registration is successfull, it will note
the fact and then proceed to start the background worker. Then it will never try
again to register nor restart the worker.
The above works great in most scenarios. However there exists a corner case
where it is not optimal. Assume that a healthcheck worker for a database
receives a SIGTERM. Then the system will never try to restart it. As …

Minor tweaks during the registration of healthcheck workers

---

src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/parsing.c
src/bin/pg_autoctl/parsing.h
tests/test_extension_update.py

Install btree_gist when upgrade to >= 1.4, not just 1.4.

---

src/monitor/health_check_worker.c

A previous commit [1], rather embarrassingly, failed to notice the reset of used
memory contexts. Additionally it was missdiagnosed for PostgreSQL versions 10
and 11. A simple run with assertions enabled was enough to expose the real bug.
This commit ammends that error and in passing restructures a bit the code in
HealthCheckWorkerLauncherMain to be hopefully cleaner.
Now the launcherContext is still reset in every database scan, but objects that
need to persist, do reside in the parent context.
[1] commit 785fd533bb
Addresses issue #717

Keep the context around for as long as you need it

---

tests/test_multi_alternate_primary_failures.py
tests/test_multi_async.py
tests/test_multi_ifdown.py
tests/test_multi_maintenance.py

CI has shown some instability in multi_async tests. One trace can be seen
frequently:
```
======================================================================
ERROR: test_multi_alternate_primary_failures.test_002_001_add_two_standbys
----------------------------------------------------------------------
Traceback (most recent call last):
File "/opt/python/3.7.6/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File
"/home/travis/build/citusdata/pg_auto_failover/tests/test_multi_alternate_primary_failures.py",
line 56, in test_002_001_add_two_standbys
assert node2.has_needed_replication_slots()
File
"/home/travis/build/citusdata/pg_auto_failover/tests/pgautofailover_utils.py",
line 1561, in has_needed_replication_slots
if self.pgmajor() == 10:
File …
```

An attempt to stabilize multi_async tests

---

src/bin/pg_autoctl/fsm.c
src/monitor/group_state_machine.c
src/monitor/node_metadata.c
tests/test_multi_alternate_primary_failures.py
tests/test_multi_async.py
tests/test_multi_maintenance.py
tests/test_multi_standbys.py

With this patch we make sure that all the nodes that participage in the
quorum have reported their LSN before we select a candidate for failover.
Otherwise, we might lose committed data.
Fixes #682

Fix how many nodes need to report their LSN to perform a failover.

---

src/bin/pg_autoctl/fsm_transition.c
src/monitor/group_state_machine.c
tests/test_multi_alternate_primary_failures.py

When a primary fails, then a new primary is elected, and then the new
primary fails while the old primary is assigned the CATCHINGUP state, then
we need to make it possible for the old primary to join the new election as
a REPORT_LSN node.
Fixes #725

Allow an old primary node (demoted/catchingup) to join another election.

---

src/bin/pg_autoctl/cli_do_monitor.c
src/bin/pg_autoctl/cli_show.c
src/bin/pg_autoctl/defaults.h
src/bin/pg_autoctl/fsm.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor.c
src/bin/pg_autoctl/monitor.h
src/bin/pg_autoctl/nodestate_utils.c
src/bin/pg_autoctl/nodestate_utils.h
src/bin/pg_autoctl/parsing.c
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h
src/bin/pg_autoctl/service_keeper.c
src/monitor/expected/monitor.out
src/monitor/group_state_machine.c
src/monitor/group_state_machine.h
src/monitor/node_active_protocol.c
src/monitor/node_metadata.c
src/monitor/node_metadata.h
src/monitor/pgautofailover--1.5--1.6.sql
src/monitor/pgautofailover.sql
src/monitor/sql/monitor.sql

This allows comparing the LSN with the added notion of the current time for
the nodes, avoiding some advanced data loss hazard if a node makes progress
while being in a network split with the application nodes, and when
rejoining later we should detect if a failover happened on the other nodes
on the system.
Fixes #726.

Track nodes current timeline on the monitor.

---

src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h
src/bin/pg_autoctl/service_keeper.c

This way we allow extensions to pg_auto_failover to implement specific
processing when the otherNodes array changes, when that's needed.

Introduce hooks to implement refreshing the otherNodes array.

---

src/bin/pg_autoctl/cli_drop_node.c
src/bin/pg_autoctl/pidfile.c
src/bin/pg_autoctl/pidfile.h
tests/pgautofailover_utils.py

The following command would get stuck for 30 seconds when the pg_autoctl service was still running.
```
pg_autoctl drop node --pgdata node1 --force --destroy
```

Have drop node --force --destroy work as expected again

---

src/bin/pg_autoctl/fsm_transition.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/service_postgres_ctl.c

The removal of the postgres state file had the unintended consequence that
postgres would not start on the monitor right away. This removal was done 
to fix some errors during rejoining after a node was dropped. 
This fixes those errors in another way, that don't impacting starting of
the monitor.

Fix monitor postgres not starting up the first time

---

src/bin/pg_autoctl/cli_get_set_properties.c
src/bin/pg_autoctl/pgsql.c

When dropping the last node with candidate priority greater than zero, we
might want to change the candidate priority of the last remaining node. The
client-side implementation of the command would wait for the APPLY_SETTINGS
cycle in some cases with dropped nodes, which is unfortunate: this PR fixes
that.

Set candidate priority without waiting for state changes in more cases.

---

src/monitor/pgautofailover--1.5--1.6.sql
src/monitor/pgautofailover.sql

There was a syntax error in the upgrade scripts, making it impossible to
upgrade. This also alligns the initial sql migration and the upgrade version
with eachother with respect to comments and grants.

Fix upgrades

---

Dockerfile
Makefile
src/monitor/group_state_machine.c
src/monitor/node_active_protocol.c
src/monitor/node_metadata.c
tests/pgautofailover_utils.py
tests/test_multi_standbys.py

When all the nodes are up and running, including the primary, a switchover
has a great chance of finding that the current primary is then the best
candidate to with the primary election, making the operation a no-op.
In this PR we tweak the current primary node's candidate priority in a way
that should make it lose the election, and reset the priority when the
election is over.
Fixes #770.

Avoid re-electing primary during a switchover.

---

docs/requirements.txt

@DimCitus I discovered that my theme changes had broken the search page. This version fixes that.

Bump theme version to fix docs search

---

src/bin/pg_autoctl/pgsql.c

It might happen that a node continues streaming from a secondary after a
failover, and in that case the streaming replication protocol takes care of
maintaining the replication slot. Trying to use pg_replication_slot_advance
would then fail.
This situation currently can arise when a node is in maintenance a failover
happens, where the node in maintenance stays connected to the old-primary,
now repurposed as a secondary.
This situation could also arise when a cascading replication setup is
considered. We don't have direct support for those architectures at the
moment, though that's something of interest for the future.
Fixes #769

Fix replication slot maintenance on secondary nodes.

---

Dockerfile
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_do_demoapp.c
src/bin/pg_autoctl/cli_do_show.c
src/bin/pg_autoctl/ipaddr.c
src/bin/pg_autoctl/keeper.c
src/bin/pg_autoctl/keeper.h
src/bin/pg_autoctl/keeper_pg_init.c
src/bin/pg_autoctl/monitor_pg_init.c
src/bin/pg_autoctl/pgsql.c
tests/upgrade/Makefile
tests/upgrade/README.md
tests/upgrade/docker-compose.yml
tests/upgrade/monitor-upgrade-1.7.patch

Only exit at upgrade when the on-disk binary is ready.

---

src/monitor/pgautofailover--1.5--1.6.sql

The script to migrate from 1.4 to 1.5 did not correctly remove the old
`register_node` function. This caused issues for the migration from 1.5
to 1.6, because we remove the old `replication_state` type there. The
old `register_node` function still depended on this version of the
`replication_state` type, so it's removal was blocked.
Fixes #784

Fix problems with bad migration to 1.5

---

src/bin/pg_autoctl/pgsql.c

As seen in the field, we might have a transient problem when trying to
connect to a local Postgres instance, even when using Unix Domain Sockets.

Also retry libpq connections to a local host.

---

src/bin/pg_autoctl/cli_do_tmux.c

I have a WSL2 environment where I have a long `PATH` variable on my env. I had issues running `make cluster` and then needed to increase the allowed `PATH` length to `ARG_MAX`.

Increase allowed path env size

---

README.md

We can also get the core number dynamically but using `10` is probably sufficient in many cases.

Use more cores while installing

---

src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/service_keeper.c

We would be using PQfreemem on a PQExpBuffer, where it's expected to be
using destroyPQExpBuffer instead.
Also we were short of a call to finish the
connection to the monitor notification client when exiting from the service
keeper process, although adding this clean-up doesn't seem to impact the
valgrind reports.
Fixes #679 (again).

Per valgrind, fix some memory leaks.

---

src/bin/pg_autoctl/fsm_transition.c

The step to reach the SINGLE state could be done from a pre-existing PGDATA,
such as taken from a backup tool. In that case, the postgresql.auto.conf
might have been installed with a setting that enables synchronous
replication.
Trouble is, we're initializing the first node in the system, and when we
reach the SINGLE state any setup for sync-rep does not make sense, we know
we don't have any secondary available.
Fixes #721

Make sure to disable sync rep when initializing a primary.

---

src/monitor/node_active_protocol.c

We don't need to require the primary to be up to see `synchronous_standby_names`. 
Also there seems to be other places where we require `primary` node to be up. It makes sense to go over them and see if it is a requirement or we can loose the condition.
Fixes https://github.com/citusdata/pg_auto_failover/issues/718

Not require primary node to be up for synchronous_standby_names

---

docs/ref/pg_autoctl_create_postgres.rst
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/cli_create_node.c

This PR allows configuring the `maximum-backup-rate` setting when running `pg_autoctl create postgres`.
Fixes #780

fix: Allow setting maximum-backup-rate on create postgres step

---

src/monitor/health_check_worker.c

On MacOS, there was a situation where poll() had POLLHUP in revents,
which was not being handled by WaitForEvent. This caused poll to
continuously run, taking CPU time (up to 100%).
In spite of requesting POLLERR | POLLIN or POLLERR | POLLOUT,
poll will also potentially return POLLHUP and POLLNVAL.
[From the opengroup poll spec:](https://pubs.opengroup.org/onlinepubs/9699919799/functions/poll.html)
"In addition, poll() shall set the POLLHUP, POLLERR, and POLLNVAL flag in
revents if the condition is true, even if the application did not set the
corresponding bit in events."
We've removed the request for POLLERR from the file descriptor as it is
unnecessary and misleading.
This fix addresses the CPU usage on MacOS 11.6 when running a monitor
that cannot connect to its nodes.
Co-authored-by: …

Handle return events for poll()

---

src/bin/pg_autoctl/keeper.c
tests/pgautofailover_utils.py
tests/test_auth.py

When updating replication settings, no need to attempt a checkpoint and
restart when postgres keeper is not running. Just start the service.
Fixes #837

Bug/837 No need to checkpoint and restart if pg is not running

---

src/bin/pg_autoctl/demoapp.c
src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/pgsql.h

A recent patch in Postgres source code replaces the random() API that is
embedded in libpq client-side (and also in the backend, but we're good on
that front).
See
https://git.postgresql.org/cgit/postgresql.git/commit/?id=3804539e48e794781c6145c7f988f5d507418fa8
for details.

Fix compat with Postgres 15devel again.

---

src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/defaults.h
tests/test_auth.py

The parameters --replication-quorum, --candidate-priority, and --name can
now also be passed from the environment variables
PG_AUTOCTL_REPLICATION_QUORUM, PG_AUTOCTL_CANDIDATE_PRIORITY, and
PG_AUTOCTL_NODE_NAME.
This allows easier Dockerfile "control-at-a-distance" integration style,
where all the containers are the same with the same command, but the
environment is where you can inject container/node/pod specific options.

Add support for more environment variables.

---

.dockerignore
.gitignore
Dockerfile
Makefile
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_root.h
src/bin/pg_autoctl/cli_do_tmux.c
src/bin/pg_autoctl/cli_do_tmux.h
src/bin/pg_autoctl/cli_do_tmux_compose.c

This PR adds a new `make compose` command that works the same way as the `make cluster` command, though uses `docker-compose` to start the monitor and the Postgres nodes in a way that uses a single tmux pane.
When using `make compose` it is possible to use PGVERSION to test with a specific docker image, such as e.g. in the command `make PGVERSION=13 NODES=6 NODES_ASYNC=3 NODES_PRIOS=50,50,50,0 compose`.
Be sure to run the usual build and also `make build build-check` first, that should clean-up the local docker images you might have dangling, and hopefully make everything just work.

Implement make compose, using docker-compose for local interactive testing.

---

src/bin/pg_autoctl/debian.c
src/bin/pg_autoctl/ini_file.c
src/bin/pg_autoctl/pgsql.c

Albeit unlikely on modern server systems, memory allocation can still fail and the result, if unchecked, be null pointer dereferences. This adds a check to affected callsites of strdup to ensure allocation was successful, or abort if not.

Check return value of strdup calls

---

docker-compose.yml
src/bin/pg_autoctl/pgctl.c

Minor fixups found during #844 
- removing duplicate key from docker-compose.yml
- Handle [non-standard](https://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html) field `d_type` in log file handling

Minor: Remove duplication add error handling

---

src/bin/pg_autoctl/pgsetup.c

This is necessary for `make` to run without errors on OSX.
Co-authored-by: Jacob Champion <pchampion@vmware.com>

Include pwd.h in pg_setup.c

---

tests/test_enable_ssl.py
tests/test_ssl_cert.py

It seems that Postgres 14 implement more security checks around ownership of
the client-side root certificate, and our symlink doesn't comply with those
rules anymore in the GitHub Action environment.

Fix ssl test by ensuring the symlink is owned by root.

---

Dockerfile
tests/tablespaces/Makefile

This allows avoiding errors from debian when asking the user about their
choice of handling configuration files, when those have been edited manually
like we do on /etc/postgresql-common/createcluster.conf.

Use DEBIAN_FRONTEND noninteractive in our Dockerfile.

---

src/monitor/version_compat.c

The statement in the `foreach()` block was indented on the same level which is confusing for reader (and potentially triggers static analysis tools).

Fix incorrect indentation of foreach block

---

src/bin/pg_autoctl/monitor.c

Commit 5304068d4 changed the conditionals in the if statement making the conditions equal. Remove the dead code block. If the changes in that commit which led to this dead block weren't intentional then a different fix might be required.

Remove dead code

---

src/bin/pg_autoctl/watch_colspecs.h

The specs array member in the EventColPolicy structure is accessed by traversing it from 0 to EVENT_COLUMN_TYPE_LAST, but the array was built using MAX_COL_SPECS from the ColPolicy structure as the array size.
Not sure why this hasn't triggered an error before, am I missing something obvious?

Fix potential out of bounds array access

---

src/bin/pg_autoctl/pidfile.c

The `pid` variable is a pointer, and pointers cannot be negative. Fix the check to test the value of the pid rather than the address of the pointer.

Fix check for negative pid

---

src/bin/pg_autoctl/pgctl.h

The prototype of `pg_setup_standby_mode()` in the `pgctl.h` header file listed the argument in the wrong order compared to the implementation. The type of the arguments were equal so it still compiled fine.

Fix incorrect order of arguments in prototype

---

src/monitor/node_active_protocol.c

prinaryNode is already dereferenced at this point so there is no need
to recheck here. Remove the check and reuse the message buffer (with
a reset) to simplify the code.

Avoid NULL pointer check

---

README.md
src/bin/pg_autoctl/cli_show.c

… README to use '--formation monitor' #874.

Updated README to use '--formation monitor'.

---

src/bin/pg_autoctl/pgctl.c

Using the environment variable allows to omit the replication password from
the logs, though messes with next connection attempts. We should either call
unsetenv() once the pg_basebackup command has finished, or use the password
on the connection string.
In this tentative PR we use the password in the connection string.
Should fix #766.

Refrain from using PGPASSWORD for pg_basebackup connection.

---

.github/workflows/build-package.yml

The citusdata tooling most recent tag is now v0.8.18, so let's try that one.

Include Postgres 15 in our CI testing.

---

.github/workflows/build-package.yml
Makefile

This simplifies the maintenance of our test infra, allowing to run the same tests on the local development environment and in the automated CI.
Because citus_indent depends on a local git checkout to be able to run correctly, we still need a special target for this test, and we still need to manually install citusdata/tools in the test VM directly.

Use our docker test infrastructure on GitHub Actions.

---

Makefile

After running the valgrind session for quite some time and doing a bunch of failovers, the valgrind report still is empty.
Fixes #914 then.

Fix make valgrind-session.

---

Dockerfile

The citus_columnar.so file is only produced starting at Citus 11, not before that. To be compatible with previous versions if Citus, use a wildcard in the filenames in the Dockerfile COPY command.

Fix Dockerfile compat for Citus before 11.

---

src/monitor/metadata.c
src/monitor/metadata.h

The checkPgAutoFailoverVersion() function was defined having a bool return type, but in practice it could only return true as the error paths were using ereport() which doesn't return. No callers of the function inspected the return value for good reason. Refactor to a void function which better match reality.
While there, also make sure that that fast-exit path is taken before any memory is allocated.

Make checkPgAutoFailoverVersion void

---

Dockerfile
Makefile
src/bin/pg_autoctl/.gitignore
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/defaults.h

Also fix the version number used when building pg_autoctl to reflect the current state of the git repository, so that the current build is given the version string "2.0-5-gef0bac49-dirty" and not just "2.0" like the latest release.

Fix pg_autoctl version Postgres compatibility string.

---

.dockerignore
.github/workflows/run-tests.yml
Dockerfile.docs
Makefile
docs/citus-quickstart.rst
docs/how-to.rst
docs/index.rst
docs/tutorial.rst

We have lots of documentation and the main navigation is crowded, so split
it in several chapters with clear names.
Also, allow to build (and serve) the docs from a docker image to make it
easy for contributors to check their work. This also makes it possible to
build the docs in the CI.

Add chapters to the docs navigation, allow building docs in docker.

---

src/bin/pg_autoctl/cli_common.c

When creating a node the option --dbname can be used to create a database for the application. When using Citus, that database is where pg_autoctl installs the Citus extensions, which is recommanded to be installed in a single database in your Postgres cluster.
To ease using pg_autoctl docker-compose and kubernetes, use PGDATABASE as the default value for the --dbname option, when set in the environment.
Fixes #953

Use environment PGDATABASE as the default create node --dbname.

---

src/bin/pg_autoctl/pgsql.c
src/bin/pg_autoctl/string_utils.c
src/bin/pg_autoctl/string_utils.h

The previous coding used a statically allocated array of pointers to newlines in that file, limiting our parsing abilities to files of 1024 lines maximum. Apparently that's not a good limit, so use dynamically allocated memory instead.
Fixes #991.

Fix history file parsing.

---

.github/workflows/run-tests.yml
Makefile
src/bin/lib/pg/snprintf.c
src/bin/pg_autoctl/azure.c
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/pgctl.c
src/bin/pg_autoctl/pgsetup.c
src/bin/pg_autoctl/primary_standby.c
src/bin/pg_autoctl/watch.c
src/monitor/health_check_worker.c
src/monitor/node_active_protocol.c
src/monitor/node_metadata.c
src/monitor/pg_auto_failover.c
src/monitor/version_compat.h

Build passes locally with a released version of Postgres 16.0 and still builds with previous version. Still missing CI changes to pass all the test suite with PGVERSION=16.
Fixes #1005.

Fix build with Postgres 166 libpq-dev in debian.

---

.github/workflows/run-tests.yml

Commit ae5fa55c4a deactivated the related tests due to failures. Commit 6698a7d07ca addressed the failures yet it did not re-activate the CI tests. This commit amends that.

Reactivate Github CI tests for Postgres major version 16

---

CONTRIBUTING.md
README.md
docker-compose.yml
docs/citus-quickstart.rst
docs/citus/Makefile
docs/citus/app.py
docs/citus/docker-compose.yml
docs/how-to.rst
docs/ref/pg_autoctl_do_tmux.rst
docs/tutorial.rst
docs/tutorial/Makefile
docs/tutorial/app.py
docs/tutorial/docker-compose.yml
src/bin/pg_autoctl/cli_do_root.c
src/bin/pg_autoctl/cli_do_tmux_compose.c
tests/tablespaces/Makefile
tests/tablespaces/docker-compose.yml
tests/upgrade/Makefile
tests/upgrade/README.md
tests/upgrade/docker-compose.yml

github removed docker-compose from their old images, so moving to docker compose seemed like the best solution.

Switch from docker-compose to the one build into docker (docker compose)

---

.github/workflows/run-tests.yml
Makefile
README.md
docs/azure-tutorial.rst
docs/install.rst
src/bin/pg_autoctl/azure.c
src/bin/pg_autoctl/cli_common.c
src/bin/pg_autoctl/pgctl.c
src/monitor/version_compat.h

Added build support and test matrix entry for v17. Updated `citusdata/tools`. Dropped v10 support over the board since it was inconsistent in multiple files.
I also changed Debian buster and v14 to bookworm and v16 in the README to reference the current versions.
Fixes #1048.

Add support for PostgreSQL 17

---

Dockerfile
Makefile
Makefile.citus
src/bin/pg_autoctl/cli_do_tmux_compose.c

The change from "docker-compose" to "docker compose" was broken.
Also it turns out we need to have the CITUSTAG to PGVERSION compat matrix around when preparing the "docker compose build" command line.

Fix make compose
