hapostgres/pg_auto_failover

- CHANGELOG.md
- src/bin/pg_autoctl/defaults.h
Tracking changes for the release of 1.0.1 (#7)
> Release 1.0.1

- CHANGELOG.md
- src/bin/pg_autoctl/defaults.h
- update the changelog
- update the version number for pg_autoctl
> Prepare release 1.0.2

- docs/operations.rst
- Use autoctl role, autoctl_node does not have enough privileges
- Add notes about controlled switchover
Fixes #25.
> Improve documentation of operating pg_auto_failover.

- src/bin/pg_autoctl/cli_config.c
- src/bin/pg_autoctl/cli_create_drop_node.c
- src/bin/pg_autoctl/cli_do_root.c
- src/bin/pg_autoctl/cli_root.c
- src/bin/pg_autoctl/cli_service.c
- src/bin/pg_autoctl/cli_show.c
- src/bin/pg_autoctl/cli_systemd.c
- src/bin/pg_autoctl/ipaddr.c
- src/bin/pg_autoctl/monitor_config.c
- src/bin/pg_autoctl/monitor_pg_init.c
- src/bin/pg_autoctl/pgsetup.c
- src/monitor/health_check_worker.c
- src/monitor/replication_state.c
- src/monitor/version_compat.h
> Fix PG12 build breaks and unused_variable warnings

- tests/network.py
DESCRIPTION: fix an issue in the test suite that was limiting the amount of virtual nodes that could be created.
The test suite had a flaw where only 55 virtual nodes could be created. This caused added tests to fail 'randomly' while succeeding in isolation. By correctly closing both the uses of IPDB and IPRoute we can now create upto 168 virtual nodes before running into the same flaw again.
It is unclear what the current limitation is, but this gives us enough headroom for the foreseeable future to keep adding tests.
Special thanks to Hadi for finding the missing release calls.
> Release ipdb and iproute to avoid resource exhaustion in tests (#226)

- .travis.yml
We are also switching to ubuntu 18.04 (bionic) for release tests. There is some python related changes needed in travis file
> Enable PG12 test in travis

- src/bin/pg_autoctl/cli_do_monitor.c
- src/bin/pg_autoctl/fsm.c
- src/bin/pg_autoctl/keeper.c
- src/bin/pg_autoctl/keeper_pg_init.c
- src/bin/pg_autoctl/loop.c
- src/bin/pg_autoctl/monitor.c
- src/bin/pg_autoctl/monitor.h
- src/bin/pg_autoctl/monitor_pg_init.c
- src/bin/pg_autoctl/pgsql.c
- src/bin/pg_autoctl/pgsql.h
- src/bin/pg_autoctl/primary_standby.h
- src/monitor/group_state_machine.c
- src/monitor/group_state_machine.h
- src/monitor/node_active_protocol.c
- src/monitor/node_metadata.c
- src/monitor/node_metadata.h
- src/monitor/notifications.c
- src/monitor/notifications.h
- src/monitor/pgautofailover.sql
- tests/test_auth.py
- tests/test_basic_operation.py
- tests/test_basic_operation_listen_flag.py
there is an issue with secondary getting stuck in catching up state
> Report current LSN of Postgres nodes rather than WAL lag.

- .travis.yml
travis updated the active python version we depend on, making our tests compatible with that
> Update python version in travis tests

- README.md
> Add documentation link to readme.md

- src/bin/pg_autoctl/config.c
- src/bin/pg_autoctl/config.h
- src/bin/pg_autoctl/debian.c
- src/bin/pg_autoctl/debian.h
- src/bin/pg_autoctl/file_utils.c
- src/bin/pg_autoctl/file_utils.h
- src/bin/pg_autoctl/keeper_pg_init.c
- tests/pgautofailover_utils.py
- tests/test_debian_clusters.py
Contains items for satisfying  #135 
Did some basic testing
Opening PR to verify the basic idea
> Support debian ubuntu style clusters

- src/bin/pg_autoctl/cli_common.c
- src/bin/pg_autoctl/cli_config.c
- src/bin/pg_autoctl/cli_create_drop_node.c
- src/bin/pg_autoctl/cli_do_fsm.c
- src/bin/pg_autoctl/cli_service.c
- src/bin/pg_autoctl/cli_show.c
- src/bin/pg_autoctl/keeper_pg_init.c
- src/bin/pg_autoctl/monitor.c
- src/bin/pg_autoctl/pgsql.c
- src/bin/pg_autoctl/primary_standby.c
This fixes some more issues found by static analysis tools. They are separate
from the fixes in #183. Since that PR can almost be merged these are done in a
new PR.
> Second batch of static analysis fixes

- src/bin/pg_autoctl/cli_common.c
- src/bin/pg_autoctl/cli_create_drop_node.c
- src/bin/pg_autoctl/cli_do_fsm.c
- src/bin/pg_autoctl/cli_do_misc.c
- src/bin/pg_autoctl/cli_perform.c
- src/bin/pg_autoctl/cli_show.c
- src/bin/pg_autoctl/ini_file.c
- src/bin/pg_autoctl/loop.c
- src/bin/pg_autoctl/monitor.c
- src/bin/pg_autoctl/parsing.c
- src/bin/pg_autoctl/parsing.h
- src/bin/pg_autoctl/pgctl.c
- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/pgsql.c
- src/bin/pg_autoctl/string_utils.c
- src/bin/pg_autoctl/string_utils.h
Adds stringToInt and stringToUint functions, and replaces existing sscanf/strtol usages with this functions
> Introduce string_utils for string functions

- src/bin/pg_autoctl/cli_common.c
- src/bin/pg_autoctl/cli_create_drop_node.c
- src/bin/pg_autoctl/debian.c
- src/bin/pg_autoctl/keeper.c
- src/bin/pg_autoctl/keeper_config.c
- src/bin/pg_autoctl/monitor_config.c
- src/bin/pg_autoctl/state.c
- src/bin/pg_autoctl/state.h
Explain the rest of the usages and add IGNORE-BANNED
> Remove most memcpy usages

- src/bin/pg_autoctl/defaults.h
- src/bin/pg_autoctl/state.c
- src/bin/pg_autoctl/state.h
> Replace ctime with ctime_r

- .travis.yml
- src/bin/pg_autoctl/Makefile
- src/bin/pg_autoctl/cli_common.c
- src/bin/pg_autoctl/debian.c
- src/bin/pg_autoctl/pghba.c
- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/pgsql.c
I added `-Wall` in an earlier PR, this fixes the issues that it finds.
> Fix warnings that GCC 7.4.0 throws

- src/bin/pg_autoctl/cli_root.c
- src/bin/pg_autoctl/monitor.c
- src/monitor/node_active_protocol.c
- tests/pgautofailover_utils.py
That way we can release from the master's branch again, and give users a
software that makes sense while preparing our next big feature and having
all the features in the code, only disabled in the release build.
> Prevent from creating more than one standby node.

- src/bin/pg_autoctl/defaults.h
- src/bin/pg_autoctl/monitor_pg_init.c
- src/bin/pg_autoctl/pgctl.c
- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/primary_standby.c
- tests/pgautofailover_utils.py
- tests/test_ssl_self_signed.py
This is the Microsoft approved cipherlist for OpenSSL applications.
> Change default TLS cipherlist

- .gitattributes
- .travis.yml
- ci/banned.h.sh
- src/bin/pg_autoctl/cli_get_set_properties.c
- src/bin/pg_autoctl/cli_show.c
- src/bin/pg_autoctl/keeper_config.c
- src/bin/pg_autoctl/monitor.c
- src/bin/pg_autoctl/pgsql.c
Checks both for correct indentation and disallows use of banned APIs.
> Actually run the linting scripts we have in ci

- src/bin/pg_autoctl/file_utils.c
- src/bin/pg_autoctl/file_utils.h
- src/bin/pg_autoctl/primary_standby.c
- tests/test_ssl_self_signed.py
Fixes problems with SSL settings not being applied correctly on the standby.
> Fix ssl_cert_file/ssl_key_file being incorrect on standby

- .travis.yml
- tests/pgautofailover_utils.py
- tests/ssl_cert_utils.py
- tests/test_enable_ssl.py
- tests/test_ssl_cert.py
- tests/test_ssl_self_signed.py
Work in progress, refactoring only at the moment.
See #248.
> Add SSL tests to upgrade from require to verify-ca.

- src/bin/pg_autoctl/cli_show.c
And by default pg_autoctl show file now outputs a human-readable tabular format.
> pg_autoctl show file ... --content --json

- src/bin/pg_autoctl/pgctl.c
We might have to download a fair amount of data from the other node, it's
best that the users see the progress as it is being made.
> Stream the output of pg_rewind while the command is running.

- src/bin/pg_autoctl/README.md
- src/bin/pg_autoctl/cli_common.c
- src/bin/pg_autoctl/cli_create_drop_node.c
- src/bin/pg_autoctl/cli_do_fsm.c
- src/bin/pg_autoctl/cli_do_service.c
- src/bin/pg_autoctl/cli_enable_disable.c
- src/bin/pg_autoctl/fsm_transition.c
- src/bin/pg_autoctl/keeper.c
- src/bin/pg_autoctl/keeper_config.c
- src/bin/pg_autoctl/keeper_pg_init.c
- src/bin/pg_autoctl/lock_utils.c
- src/bin/pg_autoctl/main.c
- src/bin/pg_autoctl/monitor.c
- src/bin/pg_autoctl/monitor_config.c
- src/bin/pg_autoctl/monitor_pg_init.c
- src/bin/pg_autoctl/pgctl.c
- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/pgsql.c
- src/bin/pg_autoctl/primary_standby.c
- src/bin/pg_autoctl/service_keeper.c
- src/bin/pg_autoctl/service_monitor.c
- src/bin/pg_autoctl/state.c
- src/bin/pg_autoctl/systemd_config.c
Standardize on american vs british english as well as a few other small fixes. See commit messages for more information.
> Spelling tweaks

- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/service_keeper.c
> Fix elapsed time display and keeper state update.

- tests/test_multi_standbys.py
Which ensures that pg_auto_failover can stay operational even if the primary
and the mostAdvancedLSN secondary becomes inaccessible
I opened a PR for a single test for now (a) for ease of review (b) get some feedback before adding other tests
> Add a regression test for multiple standbys

- src/bin/pg_autoctl/cli_common.c
- src/bin/pg_autoctl/cli_common.h
- src/bin/pg_autoctl/cli_create_drop_node.c
- src/bin/pg_autoctl/cli_do_monitor.c
- src/bin/pg_autoctl/cli_enable_disable.c
- src/bin/pg_autoctl/cli_get_set_properties.c
- src/bin/pg_autoctl/cli_service.c
- src/bin/pg_autoctl/fsm.c
- src/bin/pg_autoctl/keeper.c
- src/bin/pg_autoctl/keeper.h
- src/bin/pg_autoctl/keeper_config.c
- src/bin/pg_autoctl/keeper_config.h
- src/bin/pg_autoctl/keeper_pg_init.c
- src/bin/pg_autoctl/monitor.c
- src/bin/pg_autoctl/monitor.h
- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/pgsql.h
- src/bin/pg_autoctl/service_keeper.c
- src/monitor/expected/monitor.out
- src/monitor/formation_metadata.c
- src/monitor/group_state_machine.c
- src/monitor/node_active_protocol.c
- src/monitor/node_metadata.c
- src/monitor/node_metadata.h
- src/monitor/notifications.c
- src/monitor/notifications.h
- src/monitor/pgautofailover.sql
- src/monitor/sql/monitor.sql
- tests/pgautofailover_utils.py
- tests/test_basic_operation.py
Nodes already have an id, and then technical information to connect to them
such as the hostname and port. In this PR we add the notion of a node name.
This PR replaces #249.
> Implement a node name.

- src/bin/pg_autoctl/fsm.c
- src/bin/pg_autoctl/fsm_transition.c
All states should have a path to SINGLE, you never know.
Fixes #354
> Allow transition from REPORT_LSN to SINGLE.

- .travis.yml
- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/primary_standby.c
- src/bin/pg_autoctl/supervisor.c
- src/monitor/metadata.c
- src/monitor/node_metadata.c
- src/monitor/pg_auto_failover.c
- src/monitor/version_compat.c
- src/monitor/version_compat.h
Re-opening #297 with my MSFT account.
> Add support for building against Postgres 13

- src/bin/pg_autoctl/monitor_pg_init.c
- tests/test_multi_async.py
> Improve testing for pre-existing Postgres directory in monitor init.

- src/monitor/group_state_machine.c
- tests/pgautofailover_utils.py
- tests/test_ensure.py
> Fix unhealthy node detection when reported by pg_autoctl.

- docs/tikz/arch-single-standby.svg
- docs/tikz/arch-single-standby.tex
This was a regression introduced by #390 because of a copy pasting.
> Remove split rectangle from single standby diagram

- src/bin/pg_autoctl/monitor.c
> Implement proper signal handling in select calls.

- src/monitor/node_active_protocol.c
- src/monitor/pgautofailover.sql
> Adjust formation->number_sync_standbys when dropping a node.

- CHANGELOG.md
- README.md
- src/bin/lib/pg/snprintf.c
- src/bin/lib/pg/strerror.c
- src/bin/pg_autoctl/cli_common.c
- Edit CHANGELOG release date
- Add mentions of support of Postgres 13 (README, version string)
- Update vendored-in libs including Postgres source code
> Release 1.4.0

- CONTRIBUTING.md
Resolves: https://github.com/citusdata/pg_auto_failover/issues/443
> Add documentation about how to run tests to CONTRIBUTING.md

- docs/install.rst
> Update documentation to use pg_auto_failover 1.4 with Postgres 12.

- src/bin/pg_autoctl/file_utils.c
- src/bin/pg_autoctl/file_utils.h
- src/bin/pg_autoctl/pgsetup.c
> Avoid a race condition between file_exists() and read_file().

- src/bin/pg_autoctl/cli_do_misc.c
- src/bin/pg_autoctl/pgctl.c
Only in comments, nothing exciting to see here.
> Fix various misspellings of Posgres/PostgreSQL

- src/bin/pg_autoctl/file_utils.c
- src/bin/pg_autoctl/pgsetup.c
- src/monitor/conninfo.c
- src/monitor/formation_metadata.c
- src/monitor/node_metadata.c
This PR fixes some of the issues that semmle analysis tool found as part of the security review.
We also have some warning in file_utils that I am not sure if/how we should fix:
The errors are false-positives after this PR.
> Fix semmle issues

- src/bin/pg_autoctl/monitor.c
- src/bin/pg_autoctl/monitor_pg_init.c
> Make it obvious when an extension is missing.

- tests/pgautofailover_utils.py
- tests/test_basic_operation.py
- tests/test_multi_async.py
- tests/test_multi_ifdown.py
- tests/test_multi_maintenance.py
- tests/test_multi_standbys.py
> Refactor synchronous_standby_names checks in test suite.

- src/bin/pg_autoctl/service_postgres_ctl.c
> Fix retry loops with wait time to stop using 100% CPU.

- src/bin/pg_autoctl/systemd_config.c
- src/bin/pg_autoctl/systemd_config.h
> Add support for systemd ExecReload option.

- docs/security.rst
> Review some confusing SSL documentation.

- .gitignore
- Dockerfile
- Makefile
- src/bin/pg_autoctl/cli_do_root.c
- src/bin/pg_autoctl/cli_do_tmux.c
- src/bin/pg_autoctl/cli_do_tmux.h
- src/tools/pg_autoctl.valgrind
You can run cluster using valgrind with:
```
make cluster VALGRIND=1
```
> Add support to make cluster for valgrind

- src/bin/pg_autoctl/cli_do_tmux.c
- src/bin/pg_autoctl/parsing.c
- src/bin/pg_autoctl/pgsetup.c
- src/bin/pg_autoctl/pgsql.c
> Fix a memory leak in uri_contains_password.

- src/bin/pg_autoctl/pgsql.c
> Fix a memory leak in BuildNodesArrayValues.

- Makefile
- src/bin/pg_autoctl/main.c
I ran make cluster with
```
make cluster -j20 TMUX_LAYOUT=tiled NODES=3
```
> Fix a few issues that I ran into when running make cluster

- src/monitor/health_check_metadata.c
When a node is being dropped, the DELETE and the health check UPDATE might
work concurrently, and the monitor's code that drives the UPDATE failed to
check that a row was processed by the SPI query.
See #719 where @gkokolatos has done a great detective work!
> Fix a race condition issue around health check updates.

- .travis.yml
- Makefile
- src/bin/pg_autoctl/Makefile
- src/bin/pg_autoctl/cli_common.c
- src/bin/pg_autoctl/cli_do_tmux.c
- src/bin/pg_autoctl/parsing.c
- src/monitor/version_compat.h
> Allow building pg_auto_failover with Postgres 14.

- src/monitor/pg_auto_failover.c
The Process Utility Hook signature has changed in beta2, we need to adjust
to the new signature for those versions.
> Fix Postgres 14 beta2 incompatibility.

- docs/operations.rst
- docs/ref/pg_autoctl_config_set.rst
- docs/ref/pg_autoctl_show_state.rst
> Review and update docs with the recent PRs.

- src/bin/pg_autoctl/pgsql.c
When opening a transaction using `pgsql_begin` we would set the
connection type to multi statement mode. However, if we failed to open a
connection, we would not reset it to single statement mode.
This changes it such that we only set the connection type to multi
statement mode once we have successfully opened a transaction.
See #746
> Fix transaction begin failure handling

- src/bin/pg_autoctl/pgsql.c
The statement type needs to be set to MULTI before running BEGIN.
> Fix pgsql_begin after breaking it in a previous PR

- docs/_static/css/citus.css
- docs/conf.py
- docs/requirements.txt
Please leave this PR open so that accessibility auditors can view it in staging.
> Use citus fork of theme for accessibility

- src/bin/pg_autoctl/debian.c
> Improve error messages for missing configuration files.

- CONTRIBUTING.md
When I tried to do `make pdf` I got some error due to missing styles on my system. I resolved that by installing more OS packages that are optional.
<details>
<summary>Error Message</summary>
```
bash$ make pdf
make -s -C docs/tikz pdf
Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
Latexmk: applying rule 'lualatex'...
Rule 'lualatex': File changes, etc:
Non-existent destination files:
'arch-single-standby.pdf'
------------
Run number 1 of rule 'lualatex'
------------
------------
Running 'lualatex  --interaction=nonstopmode -shell-escape -recorder  "arch-single-standby.tex"'
------------
This is LuaTeX, Version 1.07.0 (TeX Live 2019/dev/Debian)
system commands enabled.
(./arch-single-standby.tex
LaTeX2e <2018-12-01>
luaotfload | main : initialization completed in …
```
> Add docs for installing tex styles

- src/monitor/node_active_protocol.c
Without this fix, we could register first a node that is not meant to be a
primary. The node then is assigned REPORT_LSN, but there is no primary in
the group yet, and now, all the other nodes fail to register because there
is already a node registered, but there is no primary...
> Fix a race condition in node registration.

- src/bin/pg_autoctl/Makefile
> Fix build on FreeBSD (sempahore union support).

- docs/_static/css/citus.css
Fixes accessibility issue 1793792
> Override style to ensure there is a focus ring on buttons

- src/bin/pg_autoctl/cli_drop_node.c
- src/bin/pg_autoctl/pidfile.c
> Bug fix: if process is stopped, refrain from signaling PID 0.

- docs/fault-tolerance.rst
> Fix documentation of health_check_period to match code

- README.md
> Trivial punctuation fix to README.md

- docs/citus-quickstart.rst
- docs/ref/pg_autoctl_create_postgres.rst
- docs/ref/pg_autoctl_status.rst
- docs/security.rst
- docs/tutorial.rst
- src/bin/lib/README.md
- src/bin/pg_autoctl/README.md
- src/bin/pg_autoctl/cli_create_node.c
Fixing typos and removing an option which isn't available (AFAICT). The individual commit messages have more information.
> Small documentation and user-facing messaging tweaks

- Makefile
- docs/citus/Makefile
In passing, improve our docs/citus/Makefile.
> Update Citus from 11.1.2 to 11.1.3 in our build system.

- docs/ref/pg_autoctl_do_pgsetup.rst
Correct minor typo in pg_autoctl_do_pgsetup.rst
> Fix minor typo in pg_autoctl_do_pgsetup.rst

- Makefile
- docs/conf.py
- tests/pgautofailover_utils.py
- tests/tablespaces/test_tablespaces_03.py
- tests/tablespaces/test_tablespaces_04.py
- tests/tablespaces/test_tablespaces_05.py
- tests/tablespaces/test_tablespaces_06.py
Should also bring the CI back to green with Citus fixes when building with Postgres 14 (API changes did break the build).
> Update Citus version matrix with new Citus releases.
